name: Build Book

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install --upgrade pip
          pip install chess requests
      - run: python filter_and_build.py
      - uses: actions/upload-artifact@v4
        with:
          name: book
          path: |
            crazyhouse.pgn
            crazyhouse.bin
